### PR TITLE
cleanup script folder:

### PR DESCRIPTION
**Pull request by Vethanis**
- pragma once in headers
- consistent whitespace settings + ctrl+k+d
- static function prototypes
- consistent includes

### CODE REVIEW

**Review by viviicat — APPROVED** [review]
Seems good. I have a couple of branches with in progress changes but I can just deal with the merge as it's ultimately not a lot of code.

I fixed my VS settings for whitespace in C/C++. Wondering if there's a way to tell VS to use 4 spaces for the project for anyone who clones, since the default for C is apparently to keep tabs.

**Comment by viviicat** [comment]
Seems you could add an .editorconfig file with the appropriate settings.

**Comment by gheshu** [comment]
Cool, thanks for the review Vivi!
An editorconfig or clangformat file sounds like a good idea.
I wonder if there is a way to turn my current settings into a config without manually learning each setting name and hand copying.

**Comment by viviicat** [comment]
@gheshu https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

**Comment by gheshu** [comment]
Interesting. looks like only C# has this though sadly. C/C++ have ClangFormat.

**Pull request merged**
